version: '3.7'
services:
  test-unit:
    build: .
  test-rails-4.1:
    build:
      context: .
      dockerfile: Dockerfile-rails-4.1
  test-rails-5.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.0
  test-rails-5.1:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.1
  test-rails-5.2:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.2
  test-rails-6.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-6.0
