version: '3.7'
services:
  rubocop:
    build: .
    command: bundle exec rubocop
  test-unit:
    build: .
  test-rails-5.2:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.2
  test-rails-6.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-6.0
  test-rails-6.1:
    build:
      context: .
      dockerfile: Dockerfile-rails-6.1
  test-rails-7.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-7.0
